### ISSUE TITLE
Current surveys, empty screen

### ISSUE THREAD

**Issue by brainlava** [BSiLabs/RateTheMeet#2]
When I first log into the app, I see a current surveys screen that is empty. I would suggest providing some context on the empty screen about what I should do next.

![image](https://user-images.githubusercontent.com/13080349/58120070-76eb6e00-7bd2-11e9-9845-7779968f9a3e.png)

**Comment by emilystanek** [comment]
Are you a part of any groups?

**Comment by mjfara** [comment]
I'm wondering if the latest version was released to iOS. We added that no groups card here already. Emily can you create an issue to "add version number to side menu"? Will help in the long run.

**Comment by emilystanek** [comment]
Yeah, good plan.

**Comment by brainlava** [comment]
Hey, folks, I see this when I log into the app and I am part of groups, but none of them had any surveys.

**Comment by mjfara** [comment]
Ahh right, thanks Nicole. Emily, maybe we can create another card here saying your groups have no surveys, a button to go to the groups page. Then we can start adding some more information to the group page, like the ability to notify the organizer of the app and possibly even info for the next event.
