### ISSUE TITLE
Able to submit multiple responses to one survey

### ISSUE THREAD

**Issue by tmarmer** [BSiLabs/RateTheMeet#4]
Steps to recreate:
1. Enter whatever you want to answer a survey
2. Click Submit then quickly press back (phone button or back button at the top of app)
3. Repeat

This will submit a survey response but not update the front-end to hide the survey unless you refresh the page. This allows for multiple submissions to one survey.

**Comment by mjfara** [comment]
Ah yes, makes sense. What we can do here Emily, is disable the tap command on SurveyList while the list is still loading. Or we could send an additional parameter when navigating back called "RemoveSurvey" with the survey's Id as the value. Upon checking this when navigated to, remove the associated survey from the SurveyList before re-loading. This way we're not waiting on a data call to clear the finished survey.

Thanks for the thorough testing Thomas.

**Comment by mjfara** [comment]
Fixed
