### ISSUE TITLE
Swiping animation is covering text

### ISSUE THREAD

**Issue by roxannawong** [BSiLabs/RateTheMeet#5]
![image](https://user-images.githubusercontent.com/50750680/58262590-8ab8e080-7d48-11e9-824f-4a515f025cc7.png)

I can't move my cursor to the text that the swiping animation.

Maybe we can move that to the end of screen or maybe have the submit button on the same page?

**Comment by mjfara** [comment]
Good find, we can't have submit on same page because a survey can have many questions and submit is for the whole survey. We'll look into making sure this stays outside of text bounds.
