### ISSUE TITLE
New survey doesn't appear in list immediately

### ISSUE THREAD

**Issue by roxannawong** [BSiLabs/RateTheMeet#6]
Steps to Reproduce: 

1. Make a new survey.
2. Create a question.
3. Click the save icon.
3. Before publishing, back out to Home.
4. _All changes are lost._

Maybe we could have a "you have unsaved changes" prompt?

**Comment by mjfara** [comment]
Hmm we do have this, did you type anything into the question or did it remain empty?

**Comment by roxannawong** [comment]
Ah, I know what I did now.  Edited the steps.  I was getting 'save' and 'publish' confused.

**Comment by mjfara** [comment]
I'm still unable to reproduce, are you adding any text to the question?

**Comment by mjfara** [comment]
I'm still unable to reproduce this.

**Comment by roxannawong** [comment]
I figured it out - I need to scroll around or refresh the Home screen to see the new draft survey

**Comment by mjfara** [comment]
Ah ok, that screen should refresh automatically in 1-2 seconds. We'll look into updating that locally instead of waiting on the server call.
