### ISSUE TITLE
Greyed out group photo looks like it's inactive

### ISSUE THREAD

**Issue by roxannawong** [BSiLabs/RateTheMeet#8]
Because the Meetup group photos are greyed out, I constantly think it's inactive for some reason and try to click it to try to activate it (even though there's no reason to).

![image](https://user-images.githubusercontent.com/50750680/58266119-0ddd3500-7d4f-11e9-93fe-22dea1fe31e2.png)
![image](https://user-images.githubusercontent.com/50750680/58266129-12095280-7d4f-11e9-8e01-8ffef15d3d0d.png)

**Comment by mjfara** [comment]
The gray scale was a stylistic choice to keep a simple colour scheme. We'll remove it and see how things look with some colour.

**Comment by emilystanek** [comment]
I'm thinking if we change the opacity of the images from 0.3 to around 0.8, it won't look "grayed out"

**Comment by mjfara** [comment]
Feel free to tinker with opacity and grayscale, I'm open to anything here
